export const storeProducts = [
  {
    id: 1,
    title: "Birkenstock Slides",
    img: "img/product-1.jpg",
    price: 5000,
    style: "Casual",
    info: "Genuine black suede, handmade .",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 2,
    title: "Black Birkenstock Sandal",
    img: "img/product-2.jpg",
    price: 7000,
    style: "Casual",
    info: "genuine black suede Handmade",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 3,
    title: "Cozy Crocs",
    img: "img/product-3.jpg",
    price: 7000,
    style: "Comfy/casual",
    info: "handmade",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 4,
    title: "Ox-blood Kiltie loafer with patina toe",
    img: "img/product-4.jpg",
    price: 13000,
    style: "Traditional / Semi-formal",
    info: "genuine oxblood leather, crepe sole, single heel",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 5,
    title: " corporate combo: Oxford Shoe + Belt",
    img: "img/product-5.jpg",
    price: 18000,
    style: "Corporate/semi-formal wear",
    info: "genuine sand brown leather, crepe sole, double heel",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 6,
    title: "Double monkstraps with cap toe",
    img: "img/product-6.jpg",
    price: 15000,
    style: "Corporate/semi-formal wear",
    info: "Genuine black calf leather, crepe sole, double heel",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 7,
    title: "Chukka boot",
    img: "img/product-7.jpg",
    price: 17000,
    style: "Corporate/semi-formal wear",
    info: "genuine brown leather, crepe sole, single heel",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 8,
    title: "Black Buckle Palms",
    img: "img/product-8.jpg",
    price: 6000,
    style: "Traditional/casual wear",
    info: "genuine black calf leather, foamy insole for comfort",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 9,
    title: "Tongue slides with Chinese collar",
    img: "img/product-9.jpg",
    price: 7000,
    style: "Casual / comfy",
    info: "multicoloured fabric, black leather lining, crepe sole.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 10,
    title: "Birkenstock slides",
    img: "img/product-10.jpg",
    price: 5000,
    style: "Casual",
    info: "genuine black suede",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 11,
    title: "Hightops",
    img: "img/product-11.jpg",
    price: 2,
    style: "Corporate",
    info:
      "Lorem ipsum dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha paleo. Brooklyn sriracha semiotics, DIY coloring book mixtape craft beer sartorial hella blue bottle. Tote bag wolf authentic try-hard put a bird on it mumblecore. Unicorn lumbersexual master cleanse blog hella VHS, vaporware sartorial church-key cardigan single-origin coffee lo-fi organic asymmetrical. Taxidermy semiotics celiac stumptown scenester normcore, ethical helvetica photo booth gentrify.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 12,
    title: "Hightops",
    img: "img/product-12.jpg",
    price: 18000,
    style: "Corporate",
    info:
      "Lorem ipsum dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha paleo. Brooklyn sriracha semiotics, DIY coloring book mixtape craft beer sartorial hella blue bottle. Tote bag wolf authentic try-hard put a bird on it mumblecore. Unicorn lumbersexual master cleanse blog hella VHS, vaporware sartorial church-key cardigan single-origin coffee lo-fi organic asymmetrical. Taxidermy semiotics celiac stumptown scenester normcore, ethical helvetica photo booth gentrify.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 13,
    title: "Brown Simple Palms",
    img: "img/product-13.jpg",
    price: 2500,
    style: "Casual / Traditional",
    info:
      "Lorem ipsum dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha paleo. Brooklyn sriracha semiotics, DIY coloring book mixtape craft beer sartorial hella blue bottle. Tote bag wolf authentic try-hard put a bird on it mumblecore. Unicorn lumbersexual master cleanse blog hella VHS, vaporware sartorial church-key cardigan single-origin coffee lo-fi organic asymmetrical. Taxidermy semiotics celiac stumptown scenester normcore, ethical helvetica photo booth gentrify.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 14,
    title: "Simple Black Slippers",
    img: "img/product-14.jpg",
    price: 2800,
    style: "Casual / Traditional",
    info:
      "Lorem ipsum dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha paleo. Brooklyn sriracha semiotics, DIY coloring book mixtape craft beer sartorial hella blue bottle. Tote bag wolf authentic try-hard put a bird on it mumblecore. Unicorn lumbersexual master cleanse blog hella VHS, vaporware sartorial church-key cardigan single-origin coffee lo-fi organic asymmetrical. Taxidermy semiotics celiac stumptown scenester normcore, ethical helvetica photo booth gentrify.",
    inCart: false,
    count: 0,
    total: 0,
  },
];

export const detailProduct = {
  id: 1,
  title: "Simple Black Slippers",
  img: "img/product-1.jpg",
  price: 2800,
  style: "traditional",
  info:
    "Lorem ipsum dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha paleo. Brooklyn sriracha semiotics, DIY coloring book mixtape craft beer sartorial hella blue bottle. Tote bag wolf authentic try-hard put a bird on it mumblecore. Unicorn lumbersexual master cleanse blog hella VHS, vaporware sartorial church-key cardigan single-origin coffee lo-fi organic asymmetrical. Taxidermy semiotics celiac stumptown scenester normcore, ethical helvetica photo booth gentrify.",
  inCart: false,
  count: 0,
  total: 0,
};
